- hosts: server
  vars:
  - image: rifwung3/ccid-jenkins:beta
  - python: python-docker
  tasks:
  - name: install pyhton docker centos
    yum: 
      name: "{{ python }}"
      state: present
    when:
    - ansible_distribution == "CentOS"
  - name: install python docker Ubuntu
    apt:
      name: python-pip
      state: present
    when:
    - ansible_distribution == "Ubuntu"
  - name: uninstall python-docker
    apt:
      name: python-docker
      state: absent
    when:
    - ansible_distribution == "Ubuntu"
  - name: install docker-py
    pip:
      name: docker-py
      state: present
    when:
    - ansible_distribution == "Ubuntu"  
  - name: pull images dari docker hub
    docker_image:
      name: "{{ image }}"
      state: present
      force: yes
  - name: create container
    docker_container:
      name: container_docker_jenkins
      image: "{{ image }}"
      state: started
      published_port:
      - 8090:80
      recreate: yes
